Задание 1. Реализовать tfidf датасета

In [1]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

File ‘./quora.txt’ already there; not retrieving.

In [2]:
#Установка нужных пакетов
!pip install --upgrade nltk gensim bokeh umap-learn

import itertools
import string

import numpy as np
import pandas as pd
import umap
from nltk.tokenize import RegexpTokenizer

from matplotlib import pyplot as plt

from tqdm import tqdm

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

from IPython.display import clear_output

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (3.8)
Requirement already satisfied: gensim in /usr/local/lib/python3.8/dist-packages (4.2.0)
Requirement already satisfied: bokeh in /usr/local/lib/python3.8/dist-packages (3.0.3)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.8/dist-packages (0.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk) (4.64.1)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.8/dist-packages (from gensim) (1.21.6)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.8/dist-packages (from gensim) (5.2.1)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.8/dist-packages (from gensim) (1.7.3)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.8/dist-packages (from bokeh) (21.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.8/dist-packages (from bokeh) (1.3.5)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.8/dist-packages (from bokeh) (2.11.3)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.8/dist-packages (from bokeh) (6.0.4)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.8/dist-packages (from bokeh) (2022.9.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.8/dist-packages (from bokeh) (6.0)
Requirement already satisfied: contourpy>=1 in /usr/local/lib/python3.8/dist-packages (from bokeh) (1.0.6)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.8/dist-packages (from bokeh) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=2.9->bokeh) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=16.8->bokeh) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2->bokeh) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2->bokeh) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2->bokeh) (1.15.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.8/dist-packages (from umap-learn) (0.5.8)
Requirement already satisfied: numba>=0.49 in /usr/local/lib/python3.8/dist-packages (from umap-learn) (0.56.4)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.8/dist-packages (from umap-learn) (1.0.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from numba>=0.49->umap-learn) (57.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.8/dist-packages (from numba>=0.49->umap-learn) (4.13.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.8/dist-packages (from numba>=0.49->umap-learn) (0.39.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.22->umap-learn) (3.1.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata->numba>=0.49->umap-learn) (3.11.0)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [12]:
data = list(open("./quora.txt", encoding="utf-8"))[0:100]
data[0]

"Can I get back with my ex even though she is pregnant with another guy's baby?\n"

In [13]:
def preproc(st):
  tokenizer = RegexpTokenizer(r"\w+")

  data_tok = tokenizer.tokenize(st.lower()) 

  data_word = []

  stopw = stopwords.words('english') 

  for word in data_tok:
    if word not in stopw and len(word) > 1:
      data_word.append(word)

  ## Стемминг
  # print('stemming and lemmatize')
  ps = PorterStemmer()
  lemmatizer = WordNetLemmatizer()

  data_tok_lem_stem = []

  all_lem = [ps.stem(i) for i in data_word]
  data_tok_lem_stem = [lemmatizer.lemmatize(i) for i in all_lem]

  return data_tok_lem_stem

In [14]:
def vocab(data_tok_lem_stem):
  vocab = []
  print()
  print('Составляем словарь')

  for words in tqdm(data_tok_lem_stem):
    for word in words:
      vocab.append(word)

  vocab = list(set(vocab))

  return vocab

In [15]:
def tfidf(data_tok_lem_stem, vocab):
  d = {}
  list_name = []
  list_tf = []

  print('составляем TF')
  for word in tqdm(vocab):
    list_tf = []
    for st in data_tok_lem_stem:
      i = 0
      for lem in st:

        #Находим кол_во вхождений в предложение
        if lem == word:
          i += 1 
      if i == 0:
        list_tf.append(0)
      else:
        list_tf.append(i/len(st))
    d[word] = list_tf

  df_tf = pd.DataFrame(d).T

  dict_idf = {}

  print('составляем IDF')
  for word in tqdm(vocab):
    count_doc_in = 0
    for st in data_tok_lem_stem:
      if word in st:
        count_doc_in += 1
    idf_tok = np.log(len(data_tok_lem_stem)/count_doc_in)
    dict_idf[word] = idf_tok

  df_idf = pd.DataFrame(dict_idf, index=['idf']).T
  df_tfidf = df_tf.merge(df_idf, how = 'left', left_index=True, right_index=True)

  for column in df_tfidf.columns:
    df_tfidf[column] = df_tfidf[column] * df_tfidf['idf']
  df_tfidf.drop('idf', axis = 1, inplace = True)

  return df_tfidf

In [16]:
def cosine(vector1, vector2):
  # рассчитаем скалярное произведение векторов
  numerator = np.dot(vector1, vector2)

  # (1) рассчитаем длины (по большому счету, это теорема Пифагора)
  vector1Len = np.linalg.norm(vector1)
  vector2Len = np.linalg.norm(vector2)
  
  # (2) перемножим их
  denominator = vector1Len * vector2Len

  # посмотрим, чему равен косинус угла между векторами
  cosine = numerator/denominator
  return cosine

In [17]:
data_tok_lem_stem = []
for st in tqdm(data):
  data_tok_lem_stem.append(preproc(st))
vocab = vocab(data_tok_lem_stem)

100%|██████████| 100/100 [00:00<00:00, 2655.95it/s]

Составляем словарь

100%|██████████| 100/100 [00:00<00:00, 339070.65it/s]

In [18]:
df_tfidf = tfidf(data_tok_lem_stem, vocab)

составляем TF

100%|██████████| 415/415 [00:00<00:00, 21001.63it/s]

составляем IDF

100%|██████████| 415/415 [00:00<00:00, 44233.59it/s]

In [19]:
df_tfidf

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
stock,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
le,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
base,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stuff,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
even,0.389618,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
someon,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ex,0.434669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
becom,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.535057,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
better,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
cos_dict = {}
all_list_df_tfidf = df_tfidf.T.index.to_list()

for vect1 in tqdm(all_list_df_tfidf):
  l_cos = []
  # for vect2 in df_tfidf.T.loc[vect1: df_tfidf.T.last_valid_index()].index.to_list():
  for vect2 in all_list_df_tfidf:
    cos = cosine(df_tfidf.T.loc[vect1].to_list(), df_tfidf.T.loc[vect2].to_list())
    l_cos.append(cos)
  cos_dict[vect1] = l_cos

100%|██████████| 100/100 [00:05<00:00, 17.00it/s]

In [21]:
d_cos = pd.DataFrame(cos_dict, index = list(cos_dict.keys()))
d_cos

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.041241,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.05193,0.000000,0.0,0.000000,0.0
1,0.00000,1.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.120883,0.0,0.000000,0.0
2,0.00000,0.000000,1.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.000000,0.0
3,0.00000,0.000000,0.0,1.000000,0.0,0.0,0.0,0.210244,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.062127,0.0
4,0.00000,0.000000,0.0,0.000000,1.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.05193,0.000000,0.0,0.000000,0.0,0.0,0.0,0.061091,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.00000,0.000000,0.0,0.000000,0.0
96,0.00000,0.120883,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,1.000000,0.0,0.083828,0.0
97,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,1.0,0.000000,0.0
98,0.00000,0.000000,0.0,0.062127,0.0,0.0,0.0,0.097069,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.083828,0.0,1.000000,0.0
99,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.000000,1.0

In [22]:
for i in d_cos.index.to_list():
  d_cos.at[i,i] = 0

In [23]:
dd = d_cos.merge(d_cos.max(axis = 1).to_frame(name="max_val"), left_index = True, right_index = True).sort_values('max_val', ascending = False)
dd['max_zavis_column'] = dd.idxmax()
print('Cвязанные предложения')
dd[['max_val','max_zavis_column']]

Cвязанные предложения

     max_val  max_zavis_column
11  0.505116                 3
3   0.505116                11
46  0.415945                37
37  0.415945                46
59  0.333371                23
..       ...               ...
36  0.000000                11
39  0.000000                11
40  0.000000                11
75  0.000000                11
99  0.000000                11

[100 rows x 2 columns]