[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ds-reboot/python-first-part/blob/main/notebooks/hometasks/Task1_dmrf.ipynb)

# Задание
* Собрать информацию о всех строящихся объектах на сайте "наш.дом.рф"
* Cохранить ее в pandas dataframe
* Cохранить pandas dataframe в excel
* Cохранить pandas dataframe в pickle
* Cохранить pandas dataframe в БД

# Задание *
* Написать скрипт, который скачивает фотографии всех строящихся объектов с сайта "наш.дом.рф"

In [1]:
import requests

## Список объектов

In [2]:
# Для скачивания данных по

offset_ = 1
limit_ = 100
url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/kn/object?offset={offset_}&limit={limit_}&sortField=devId.devShortCleanNm&sortType=asc&objStatus=0'
res = requests.get(url)
objects_data = res.json()
# objects_data.get('data').get('list')[0]

In [9]:
type(objects_data)

dict

In [4]:
objects_list = objects_data.get('data').get('list')
objids = [x.get('objId') for x in objects_list]
objids[:10]

[13391, 13397, 13383, 13398, 13399, 36912, 44076, 23494, 27476, 10891]

## Сохранить в пандас

In [5]:
import pandas as pd

In [14]:
data = pd.json_normalize(pd.DataFrame.from_dict(objects_data).get('data').get('list'))

In [15]:
data

,objId,rpdRegionCd,objAddr,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,objProblemFlg,...,developer.orgForm.fullForm,developer.orgForm.shortForm,developer.companyGroup,developer.devInn,objCommercNm,complexShortName,developer.bankruptStage.bankruptStageCd,developer.bankruptStage.bankruptStageDesc,developer.bankruptStage.bankruptLawUrl,developer.orgBankruptMsgDttm
0,13391,72,"г Тюмень, ул Профсоюзная",3,12,44,2022-12-31,4297.44,1,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
1,13397,72,"г Тюмень, ул Профсоюзная, д. 56",6,12,65,2024-12-31,6248.51,0,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
2,13383,72,г Тюмень,4,20,68,2022-12-31,6293.78,1,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
3,13398,72,"г Тюмень, ул Профсоюзная, д. 56",7,10,43,2024-12-31,4812.98,0,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
4,13399,72,"г Тюмень, ул Профсоюзная, д. 56",1,1,0,2024-12-31,0.00,0,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,33179,77,"д Зверево, д. 85",3,3,18,2022-12-31,1026.64,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 85",NaN,NaN,NaN,NaN,NaN
96,33191,77,"д Зверево, д. 97",3,3,18,2022-12-31,1026.64,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 97",NaN,NaN,NaN,NaN,NaN
97,33202,77,"д Зверево, д. 108",3,3,39,2022-12-31,2278.61,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 108",NaN,NaN,NaN,NaN,NaN
98,33209,77,"д Зверево, д. 115",3,3,18,2022-12-31,1026.64,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 115",NaN,NaN,NaN,NaN,NaN
99,33215,77,"д Зверево, д. 121",3,3,51,2022-12-31,2198.66,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 121",NaN,NaN,NaN,NaN,NaN

# Сохранение в пандас из файла

In [1]:
import pandas as pd

In [2]:
url = f'/Users/19282873/Downloads/python-first-part-main/notebooks/hometasks/File/homerf.json'

In [19]:
data = pd.read_json(url, orient = 'records')
# pd.json_normalize(pd.DataFrame.from_dict(data.get('data').get('list')))
# df = data.get('data').get('list')

In [37]:
pd.json_normalize(data.get('data').get('list')[i])

,objId,rpdRegionCd,objAddr,objCommercNm,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,...,pdId,buildType,objStatus,developer.devId,developer.shortName,developer.fullName,developer.orgForm.id,developer.orgForm.fullForm,developer.orgForm.shortForm,developer.devInn
0,33096,77,"д Зверево, д. 2","Сиреневый квартал, дом 2",3,3,75,2023-09-30,3390.59,0,...,77853,Жилое,0,3522,АПРЕЛЕВКА С2,АПРЕЛЕВКА С2,4,Общество с ограниченной ответственностью,ООО,5030049041

In [38]:
# Выгружаем все записи
df = pd.DataFrame()

for i in range(0,len(data.get('data').get('list'))):
    df = df.append(pd.json_normalize(data.get('data').get('list')[i]), ignore_index = True)
    
df

,objId,rpdRegionCd,objAddr,objFloorMin,objFloorMax,objElemLivingCnt,objReady100PercDt,objSquareLiving,objCompensFundFlg,objProblemFlg,...,developer.orgForm.fullForm,developer.orgForm.shortForm,developer.companyGroup,developer.devInn,objCommercNm,complexShortName,developer.bankruptStage.bankruptStageCd,developer.bankruptStage.bankruptStageDesc,developer.bankruptStage.bankruptLawUrl,developer.orgBankruptMsgDttm
0,13383,72,г Тюмень,4,20,68,2022-12-31,6293.78,1,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
1,13397,72,"г Тюмень, ул Профсоюзная, д. 56",6,12,65,2024-12-31,6248.51,0,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
2,13399,72,"г Тюмень, ул Профсоюзная, д. 56",1,1,0,2024-12-31,0.00,0,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
3,13398,72,"г Тюмень, ул Профсоюзная, д. 56",7,10,43,2024-12-31,4812.98,0,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
4,13391,72,"г Тюмень, ул Профсоюзная",3,12,44,2022-12-31,4297.44,1,0,...,Акционерное общество,АО,5776.0,7701651356,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,33101,77,"д Зверево, д. 7",3,3,18,2022-12-31,1026.64,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Сиреневый квартал, дом 7",NaN,NaN,NaN,NaN,NaN
96,33098,77,"д Зверево, д. 4",3,3,48,2022-12-31,2164.28,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Сиреневый квартал, дом 4",NaN,NaN,NaN,NaN,NaN
97,33201,77,"д Зверево, д. 107",3,3,39,2022-12-31,2278.61,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 107",NaN,NaN,NaN,NaN,NaN
98,33177,77,"д Зверево, д. 83",3,3,99,2022-12-31,4362.94,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Рябиновый квартал, дом 83",NaN,NaN,NaN,NaN,NaN
99,33096,77,"д Зверево, д. 2",3,3,75,2023-09-30,3390.59,0,0,...,Общество с ограниченной ответственностью,ООО,NaN,5030049041,"Сиреневый квартал, дом 2",NaN,NaN,NaN,NaN,NaN

In [40]:
# сохранение в excel
df.to_excel(f'/Users/19282873/Downloads/python-first-part-main/notebooks/hometasks/File/excel_1.xlsx', sheet_name = 'Sheet1')

In [43]:
# загрузка файл pickle
import pickle
df.to_pickle(f'/Users/19282873/Downloads/python-first-part-main/notebooks/hometasks/File/pickle_1')

In [1]:
# загрузка в базу

import sqlite3

conn = sqlite3.connect('test_database')
df.to_sql('products', conn, if_exists='replace', index = False)
conn.commit()
conn.close()